# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_4.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(555, 500)
        MainWindow.setMinimumSize(QtCore.QSize(555, 500))
        MainWindow.setMaximumSize(QtCore.QSize(555, 560))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 0, 211, 31))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 91, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 160, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 121, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 101, 20))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 151, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(260, 60, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(260, 110, 131, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.get_money = QtWidgets.QLineEdit(self.centralwidget)
        self.get_money.setGeometry(QtCore.QRect(260, 210, 131, 20))
        self.get_money.setObjectName("get_money")
        self.order_summary = QtWidgets.QLineEdit(self.centralwidget)
        self.order_summary.setGeometry(QtCore.QRect(360, 160, 181, 20))
        self.order_summary.setObjectName("order_summary")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 290, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.final_receipt = QtWidgets.QLineEdit(self.centralwidget)
        self.final_receipt.setGeometry(QtCore.QRect(70, 340, 441, 61))
        self.final_receipt.setObjectName("final_receipt")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(240, 210, 16, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bill Calculator "))
        self.label.setText(_translate("MainWindow", "Classic Coffee Bill Calculator "))
        self.label_4.setText(_translate("MainWindow", "Order Summary "))
        self.pushButton.setText(_translate("MainWindow", "Submit "))
        self.label_2.setText(_translate("MainWindow", "What would you like? "))
        self.label_3.setText(_translate("MainWindow", "Cup Sizes"))
        self.label_5.setText(_translate("MainWindow", "Insert The Money"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Coffee Latte"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Coffee Frappuccino"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Iced Coffee"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Tall"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Grande"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Venti"))
        self.pushButton_2.setText(_translate("MainWindow", "Buy"))
        self.label_6.setText(_translate("MainWindow", "$"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
